### ISSUE TITLE
Doesn't work with my school district

### ISSUE THREAD

**Issue by ghost** [kajchang/StudentVue#18]

**Comment by kaijchang** [comment]
@JustAnAltAccount Unfortunately can't tell much from this error, seems like the XML getting returned is invalid, but can't see it so not sure what the actual issue is. According to https://github.com/StudentVue/StudentVue.js/issues/19, StudentVue might have updated their backend, which might be causing this issue. Unfortunately, I no longer attend a StudentVue school so there's not much I can do in the way of maintaining these libraries.

**Comment by thiccaxe** [comment]
@JustAnAltAccount I cannot reproduce your issue. However, the following code: `sv = studentvue.StudentVue('1000000', 'yes', 'sisstudent.fcps.edu/SVUE')` seems to work. It seems that this url is some sort of edge case; as `https://sisstudent.fcps.edu/SVUE` triggers a codepath that drops the `/SVUE`
